footprint:
  target: test
  outputs:
    test:
      type: devnull
      schema: test
      database: test
      username: user
      password: password
      host: localhost
      threads: 1
    dev:
      type: trino
      schema: prod
      database: iceberg
      user: root
      host: 127.0.0.1
      port: 8080
      threads: 1


